### ISSUE TITLE
More defined guide to running makefile

### ISSUE THREAD

**Issue by CthompsonCL** [aws-samples/amazon-personalize-automated-retraining#2]
Hope you are well. I wanted to tell you if I could give a more precise guide on how to run the makefile to run the cloudformation stack. 

Thanks for all.

**Comment by Till--H** [comment]
Hi, this for this issue. I'll get to document this a little better in September. So that you don't have to wait until then, the steps are

- Install AWS CLI
- Fill out the parameters in [parameters.cfg](https://github.com/aws-samples/amazon-personalize-automated-retraining/blob/master/parameters.cfg); you can find a list of what the parameters are in the [Readme](https://github.com/aws-samples/amazon-personalize-automated-retraining/blob/master/README.md#deployment)
- Create an S3 bucket for Cloudformation to put some temporary resources into
- Fill this S3 bucket and your region into the Makefile
- Run `make` to execute deploy the CFN in the region specified in the Makefile
